- name: Mildly interesting facts
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.habits.facts.svg
    token: ${{ secrets.METRICS_TOKENS }}
    base: ""
    plugin_habits: yes
    plugin_habits_facts: yes
    plugin_habits_charts: no
    config_timezone: Asia/Calcutta

- name: Recent activity charts
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.habits.charts.svg
    token: ${{ secrets.METRICS_TOKENS }}
    base: ""
    plugin_habits: yes
    plugin_habits_facts: no
    plugin_habits_charts: yes
    config_timezone: Asia/Calcutta
