name: Coding Habits and Activity

on:
  schedule: [{cron: "0 0 * * *"}]  # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_trim: yes
          config_timezone: Asia/Kolkata  # Change to your local time zone
