name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
        
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Tushar0i
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Calcutta
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
